on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.x"

      - name: Install dependencies
        run: |
          npm install
          npx next telemetry disable

      - name: Lint Jobs
        run: |
          npm run lint
          npm run lint:md
          npm run lint:commit
